### ISSUE TITLE
The relation between i2p.csv and nudity.csv

### ISSUE THREAD

**Issue by CharlesGong12** [OPTML-Group/Diffusion-MU-Attack#3]
Hi, what an amzing work! I am so lucky to reproduce your code and btw I am confused about the relation between i2p.csv and nudity.csv. I see that if you select all the "sexual" categories from i2p.csv, you will have 930+ prompts but there only 140+ prompts in nudity.csv. Could you help me to figure it out? I will appreciate it! :)

**Comment by damon-demon** [comment]
Hello Chao Gong,

Thank you very much for acknowledging our work. I appreciate your attention to the details in our datasets.

I'd like to clarify the discrepancy you've noted. The reason the number of prompts in nudity.csv is smaller compared to those in the I2P dataset categorized under "sexual" is due to our selective filtering process. Specifically, we exclude images that have a nudity score (as determined by NudeNet) below our set threshold.

Should you have any further questions or need more information, please don't hesitate to reach out.

Best regards,
Yimeng

**Comment by CharlesGong12** [comment]
Thank you for addressing my issue! I appreciate your kind assistance. 💪

**Comment by CharlesGong12** [comment]
Hello, Author!
Sorry for reaching out again. I wanted to inquire about the threshold you mentioned for obtaining the "nudity.csv". Thank you so much for your assistance!
